merge: datasets/env/breakout.yml
dataset:
  steps: 50
task:
  type: rl
  model:
    type: DQN
    interactions_per_learn: 2
  datamodule:
    num_workers: 2
    batch_size: 32
run:
  action: train
  lightning:
    max_epochs: 1000
  checkpoint: runs/rl/ALE_Breakout-v5/DQN/2/lightning_logs/version_0/checkpoints/epoch=999-step=1000000.ckpt
