merge: datasets/env/breakout.yml
dataset:
  params:
    steps: 32000
task:
  identifier: rl
  model:
    type: DQN
  datamodule:
    num_workers: 2
    batch_size: 32
run:
  action: train
  lightning:
    max_epochs: 1000
