
[package]
edition = "2021"
name = "rust"
version = "0.1.0"

[lib]
path = "src/ai/rust/lib.rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21.2", features = ["gil-refs", "extension-module"] }
