[tool.poetry]
name = "ai-4-alan"
version = "0.1.0"
description = ""
authors = ["Alan Blanchet <alan@alan-blanchet.fr>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "ai", from = "src" }]

[tool.poetry.dependencies]
python = "^3.11"
attrs = "^23.1.0"
graphviz = "^0.20.1"
torch = [
    { url = "https://download.pytorch.org/whl/cpu/torch-2.0.1-cp311-none-macosx_11_0_arm64.whl", platform = "darwin" },
    { url = "https://download.pytorch.org/whl/cu118/torch-2.0.1%2Bcu118-cp311-cp311-linux_x86_64.whl", platform = "linux" },
    { url = "https://download.pytorch.org/whl/cu118/torch-2.0.1%2Bcu118-cp311-cp311-win_amd64.whl", platform = "win32" },
]
numpy = "^1.26.2"
click = "^8.1.7"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.28.0"
pytest = "^7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.scripts]
ai = "ai.cli.ai:main"
