[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]

[tool.poetry]
authors = ["Alan Blanchet <alan@alan-blanchet.fr>"]
description = ""
license = "MIT"
name = "ai-4-alan"
packages = [{ include = "ai", from = "src" }]
readme = "README.md"
version = "0.1.0"

[tool.poetry.dependencies]
python = ">=3.11,<4.0"
attrs = "^23.1.0"
click = "^8.1.7"
numpy = "^1.26.2"
easydict = "^1.11"
random-word = "^1.0.11"
moviepy = "^1.0.3"
urllib3 = "<2"
nbformat = ">=4.2.0"
# UI/VIZ
gradio = "^4.19.2"
fiftyone = "^0.23.6"
graphviz = "^0.20.1"
seaborn = "^0.13.1"
tqdm = "^4.66.1"
umap-learn = "^0.5.5"
# ML
albumentations = "^1.3.1"
tensorboardx = "^2.6.2.2"
tensorboard = "^2.15.1"
transformers = "^4.38.2"
datasets = "^2.18.0"
tiktoken = "^0.6.0"
scikit-learn = "^1.4.0"
# RL
ale-py = "^0.8.1"
gymnasium = { extras = [
  "classic-control",
  "box2d",
  "accept-rom-license",
  "atari",
], version = "^0.29.1" }
# Torch
torch = "^2.2.1"
torchvision = "^0.17.1"
torchmetrics = "^1.2.1"
lightning = "^2.2.1"
einops = "^0.7.0"
# MMlab
mmcv = { url = "https://download.openmmlab.com/mmcv/dist/cu121/torch2.1.0/mmcv-2.1.0-cp311-cp311-manylinux1_x86_64.whl" }
openmim = "^0.3.9"
mmdet = "^3.3.0"
mmocr = "^1.0.1"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.28.0"
pytest = "^7.4.3"

[tool.poetry.scripts]
ai = "ai.cli.ai:main"
