dataset:
  source: gym
  params:
    name: ALE/Breakout-v5
    max_steps: 300
  skips: 4
  input: obs
  # modalities:
  #   - type: image
  #     resize: 84
  #     augmentations:
  #       - type: CenterCrop
  #         size: 84
