merge: datasets/coco.yml
task:
  type: detection
dataset:
  input:
    name: image
    other: image_mask
  image:
    preprocess: None
    # transforms:
    #   - HorizontalFlip
    #   - OneOf:
    #       - RandomResize:
    #           - [480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800]
    #           - max_size: 1333
    #       - Compose:
    #           - RandomResize:
    #               - [400, 500, 600]
    #           - RandomSizeCrop:
    #               - 384
    #               - 600
    #           - RandomResize:
    #               - [480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800]
    #               - max_size: 1333
