class Output:
    def __init__(self, *args, **kwargs) -> None: ...
    def batch_process(self, *args, **kwargs) -> Any: ...
    def output_method(self, *args, **kwargs) -> Any: ...

class TestCastClass:
    cast_field: Output
    regular_field: str
    def __init__(self, **kwargs) -> None: ...