dataset:
  source: hf
  input: image
  labels: objects.classes
  bbox: objects.bboxes
  params:
    path: fuliucansheng/pascal_voc
    name: voc2007_main
  train:
    name: train
  val:
    name: val
